### PR TITLE
dark mode fixes

### LINKED ISSUE #331: Dark mode - UI review
Hi, 

Here are a few general comments to the dark mode theme:

- [x] menu items on the top right - please match them dark mode theme. The example of dark mode is here: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f1d2dbfaf220c37fb5fa2b1/
photo_2020-10-18 11 21 59
 

- [x] please match text input fields in dark mode to dark mode theme (no white fields)

photo_2020-10-18 12 03 37

- [x] please change accent blue color in dark mode to 156FFF

- [x] mobile menu - please change the line above the menu to 1F3A55

Thanks

### PR DESCRIPTION
**Pull request by Ran73Cohen**
#331 and other things I see

### CODE REVIEW

File: src/components/modals/ModalStake.vue [hunk 1]
```diff
@@ -143,17 +125,24 @@
...
-    MainButton
+    MainButton,
+    AlertBlock,
+    TokenInputField
   }
 })
 export default class ModalStake extends BaseComponent {
   @VModel({ type: Boolean }) show!: boolean;
 
+  gBnt: ViewToken = vxm.bancor.tokens[0];
```
Comment (Velua) [inline src/components/modals/ModalStake.vue:144]: Lets have a chat about this one over Zoom.

**Comment by Velua** [comment]
update TokenInputAmount.vue to accept a default token logo if a logo prompt is not defined
update your component not to have a ViewToken but ViewModalToken instead
go from [0] to a 
const bnt =  vxm.bancor.tokens.find(token => compareString(token.symbol, 'BNT')
if (bnt) {
   return the symbol + image
  otherwise just return the symbol

**Review by Velua — APPROVED** [review]
